name = "PkgDevTools"
uuid = "2afb0842-1d6c-4499-8b39-71b06199676f"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.1.1"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
OrderedCollections = "1"
julia = "1.5"
